In [1]:
import pandas as pd
import os 
from sqlalchemy import create_engine
import sqlite3

In [7]:
engine = create_engine(
    "mysql+pymysql://root:kajal@localhost:3306/vendor_db"
)

In [ ]:
def ingest_db_chunked(file_path, table_name, engine):
    for chunk in pd.read_csv(file_path, chunksize=5000):
        chunk.columns = chunk.columns.str.lower().str.replace(' ', '_')
        
        chunk.to_sql(
            table_name,
            engine,
            if_exists='append',
            index=False
        )

for file in os.listdir('data'):
    if file.endswith('.csv'):
        path = os.path.join('data', file)
        table_name = file.replace('.csv', '')
        
        ingest_db_chunked(path, table_name, engine

In [9]:
tables = pd.read_sql("SHOW TABLES", engine)
tables

   Tables_in_vendor_db
0      begin_inventory
1        end_inventory
2  final_sales_summary
3      purchase_prices
4            purchases
5                sales
6       vendor_invoice

In [4]:
for table in tables['Tables_in_vendor_db']:
    print('-'*50, f'{table}', '-'*50)
    print("count of reords:",pd.read_sql(f"SELECT COUNT(*) AS count FROM {table}", engine)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5",engine))

-------------------------------------------------- begin_inventory --------------------------------------------------
count of reords: 206529

,inventoryid,store,city,brand,description,size,onhand,price,startdate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
count of reords: 224489

,inventoryid,store,city,brand,description,size,onhand,price,enddate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
count of reords: 12261

,brand,description,price,size,volume,classification,purchaseprice,vendornumber,vendorname
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases --------------------------------------------------
count of reords: 2372474

,inventoryid,store,brand,description,size,vendornumber,vendorname,ponumber,podate,receivingdate,invoicedate,paydate,purchaseprice,quantity,dollars,classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales --------------------------------------------------
count of reords: 12825363

,inventoryid,store,brand,description,size,salesquantity,salesdollars,salesprice,salesdate,volume,classification,excisetax,vendorno,vendorname
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
count of reords: 5543

,vendornumber,vendorname,invoicedate,ponumber,podate,paydate,quantity,dollars,freight,approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [5]:
purchases = pd.read_sql("select * from purchases where vendornumber = 4466",engine)
purchases

In [6]:
purchase_price = pd.read_sql("select * from purchase_prices  where vendornumber = 4466 ",engine)
purchase_price

In [7]:
vendor_invoice = pd.read_sql("select * from vendor_invoice where vendornumber = 4466",engine)
vendor_invoice

In [8]:
sales = pd.read_sql("select * from sales where vendorno = 4466",engine)
sales

In [9]:
#Aggregate SALES
sales_summary = pd.read_sql("""
    SELECT
        inventoryid,
        store,
        SUM(salesquantity) AS total_sales_qty,
        SUM(salesdollars) AS total_sales_amount,
        SUM(excisetax) AS total_excise_tax
    FROM sales
    GROUP BY inventoryid, store
""", engine)

In [10]:
#PURCHASE AGGREGATION

purchase_summary = pd.read_sql("""
    SELECT
        inventoryid,
        store,
        SUM(quantity) AS total_purchase_qty,
        SUM(dollars) AS total_purchase_amount,
        AVG(purchaseprice) AS avg_purchase_price
    FROM purchases
    GROUP BY inventoryid, store;

""",engine)

In [11]:
begin_inventory_summary = pd.read_sql("""
    SELECT
        inventoryid,
        store,
        onhand AS begin_qty
    FROM begin_inventory;

""",engine)

In [12]:
end_inventory_summary = pd.read_sql("""
    select 
        inventoryid,
        store,
        onhand as end_qty
    from end_inventory
""",engine)

In [13]:
final_sales_summary = (
    begin_inventory_summary
    .merge(purchase_summary, on=['inventoryid','store'], how='left')
    .merge(sales_summary, on=['inventoryid','store'], how='left')
    .merge(end_inventory_summary, on=['inventoryid','store'], how='left')
)

In [15]:
final_sales_summary.fillna(0, inplace=True)

In [18]:
final_sales_summary['calculated_end_qty'] = (
    final_sales_summary['begin_qty']
    + final_sales_summary['total_purchase_qty']
    - final_sales_summary['total_sales_qty']
)

In [21]:
final_sales_summary['shrinkage'] = (
    final_sales_summary['end_qty']
    - final_sales_summary['calculated_end_qty']
)

In [23]:
final_sales_summary['gross_profit'] = (
    final_sales_summary['total_sales_amount']
    - final_sales_summary['total_purchase_amount']
)

In [24]:
final_sales_summary['profit_margin_pct'] = (
    final_sales_summary['gross_profit'] /
    final_sales_summary['total_sales_amount'].replace(0, pd.NA)
) * 100

In [27]:
final_sales_summary

,inventoryid,store,begin_qty,total_purchase_qty,total_purchase_amount,avg_purchase_price,total_sales_qty,total_sales_amount,total_excise_tax,end_qty,calculated_end_qty,shrinkage,gross_profit,profit_margin_pct
0,1_HARDERSFIELD_58,1,8,105.0,974.40,9.28,102.0,1272.98,80.35,11.0,11.0,0.0,298.58,23.4552
1,1_HARDERSFIELD_60,1,7,36.0,266.40,7.40,43.0,464.57,33.86,0.0,0.0,0.0,198.17,42.65665
2,1_HARDERSFIELD_62,1,6,116.0,3325.72,28.67,115.0,4443.85,90.50,7.0,7.0,0.0,1118.13,25.16129
3,1_HARDERSFIELD_63,1,3,59.0,1797.14,30.46,55.0,2244.45,43.38,7.0,7.0,0.0,447.31,19.929604
4,1_HARDERSFIELD_72,1,6,0.0,0.00,0.00,2.0,69.98,1.58,4.0,4.0,0.0,69.98,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206524,79_BALLYMENA_46985,79,13,59.0,929.25,15.75,28.0,670.72,3.08,44.0,44.0,0.0,-258.53,-38.545146
206525,79_BALLYMENA_47014,79,13,36.0,293.76,8.16,40.0,549.60,4.42,9.0,9.0,0.0,255.84,46.550218
206526,79_BALLYMENA_47090,79,19,60.0,934.80,15.58,65.0,1559.35,7.20,14.0,14.0,0.0,624.55,40.051945
206527,79_BALLYMENA_90011,79,12,2.0,189.52,94.76,5.0,724.95,0.56,9.0,9.0,0.0,535.43,73.857507
206528,79_BALLYMENA_90089,79,24,0.0,0.00,0.00,3.0,359.97,0.34,21.0,21.0,0.0,359.97,100.0

In [26]:
final_sales_summary[
    final_sales_summary['end_qty'] < 0
]

Empty DataFrame
Columns: [inventoryid, store, begin_qty, total_purchase_qty, total_purchase_amount, avg_purchase_price, total_sales_qty, total_sales_amount, total_excise_tax, end_qty, calculated_end_qty, shrinkage, gross_profit, profit_margin_pct]
Index: []

In [29]:
final_sales_summary[
    final_sales_summary['shrinkage'].abs() > 10
]

Empty DataFrame
Columns: [inventoryid, store, begin_qty, total_purchase_qty, total_purchase_amount, avg_purchase_price, total_sales_qty, total_sales_amount, total_excise_tax, end_qty, calculated_end_qty, shrinkage, gross_profit, profit_margin_pct]
Index: []

In [30]:
final_sales_summary[
    final_sales_summary['profit_margin_pct'] < 5
]

,inventoryid,store,begin_qty,total_purchase_qty,total_purchase_amount,avg_purchase_price,total_sales_qty,total_sales_amount,total_excise_tax,end_qty,calculated_end_qty,shrinkage,gross_profit,profit_margin_pct
8,1_HARDERSFIELD_115,1,5,150.0,3205.50,21.37,120.0,3358.80,126.00,35.0,35.0,0.0,153.30,4.56413
24,1_HARDERSFIELD_284,1,2,9.0,480.87,53.43,3.0,217.97,2.37,8.0,8.0,0.0,-262.90,-120.612928
63,1_HARDERSFIELD_649,1,5,24.0,688.08,28.67,18.0,689.82,14.20,11.0,11.0,0.0,1.74,0.25224
64,1_HARDERSFIELD_652,1,1,18.0,295.38,16.41,13.0,288.87,10.25,6.0,6.0,0.0,-6.51,-2.253609
90,1_HARDERSFIELD_828,1,10,12.0,92.88,7.74,7.0,69.93,7.35,15.0,15.0,0.0,-22.95,-32.818533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206406,79_BALLYMENA_43615,79,23,12.0,142.08,11.84,6.0,113.94,0.66,29.0,29.0,0.0,-28.14,-24.697209
206429,79_BALLYMENA_44083,79,4,24.0,344.88,14.37,4.0,72.96,0.44,24.0,24.0,0.0,-271.92,-372.697368
206447,79_BALLYMENA_44493,79,10,12.0,372.84,31.07,8.0,374.92,0.88,14.0,14.0,0.0,2.08,0.554785
206467,79_BALLYMENA_45266,79,0,72.0,470.16,6.53,39.0,453.61,4.31,33.0,33.0,0.0,-16.55,-3.648509
206524,79_BALLYMENA_46985,79,13,59.0,929.25,15.75,28.0,670.72,3.08,44.0,44.0,0.0,-258.53,-38.545146

In [31]:
product_info = pd.read_sql("""
    SELECT DISTINCT inventoryid, brand, description, classification
    FROM sales
""", engine)

In [32]:
final_sales_summary = final_sales_summary.merge(
    product_info,
    on='inventoryid',
    how='left'
)

In [33]:
final_sales_summary

,inventoryid,store,begin_qty,total_purchase_qty,total_purchase_amount,avg_purchase_price,total_sales_qty,total_sales_amount,total_excise_tax,end_qty,calculated_end_qty,shrinkage,gross_profit,profit_margin_pct,brand,description,classification
0,1_HARDERSFIELD_58,1,8,105.0,974.40,9.28,102.0,1272.98,80.35,11.0,11.0,0.0,298.58,23.4552,58.0,Gekkeikan Black & Gold Sake,1.0
1,1_HARDERSFIELD_60,1,7,36.0,266.40,7.40,43.0,464.57,33.86,0.0,0.0,0.0,198.17,42.65665,60.0,Canadian Club 1858 VAP,1.0
2,1_HARDERSFIELD_62,1,6,116.0,3325.72,28.67,115.0,4443.85,90.50,7.0,7.0,0.0,1118.13,25.16129,62.0,Herradura Silver Tequila,1.0
3,1_HARDERSFIELD_63,1,3,59.0,1797.14,30.46,55.0,2244.45,43.38,7.0,7.0,0.0,447.31,19.929604,63.0,Herradura Reposado Tequila,1.0
4,1_HARDERSFIELD_72,1,6,0.0,0.00,0.00,2.0,69.98,1.58,4.0,4.0,0.0,69.98,100.0,72.0,No. 3 London Dry Gin,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206524,79_BALLYMENA_46985,79,13,59.0,929.25,15.75,28.0,670.72,3.08,44.0,44.0,0.0,-258.53,-38.545146,46985.0,Rodney Strong Cab Svgn Alexa,2.0
206525,79_BALLYMENA_47014,79,13,36.0,293.76,8.16,40.0,549.60,4.42,9.0,9.0,0.0,255.84,46.550218,47014.0,Juan Gil Jumilla Rd,2.0
206526,79_BALLYMENA_47090,79,19,60.0,934.80,15.58,65.0,1559.35,7.20,14.0,14.0,0.0,624.55,40.051945,47090.0,Napa Cellars Cab Svgn Napa,2.0
206527,79_BALLYMENA_90011,79,12,2.0,189.52,94.76,5.0,724.95,0.56,9.0,9.0,0.0,535.43,73.857507,90011.0,Ch Pichon Longville 12 Pauil,2.0
206528,79_BALLYMENA_90089,79,24,0.0,0.00,0.00,3.0,359.97,0.34,21.0,21.0,0.0,359.97,100.0,90089.0,Ch Lynch Bages 12 Pauillac,2.0

In [35]:
final_sales_summary.to_sql(
    'final_sales_summary',
    engine,
    if_exists='replace',
    index=False
)

206529

In [36]:
final_sales_summary.to_csv('final_inventory_summary.csv',index=False)